name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # UTC+8 时区的每日 0:00 对应于 UTC 的前一天 16:00
    - cron: "0 16 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ### content
          SHOW_UPDATED_DATE: "True"  # 更新日期
          SHOW_PROFILE_VIEWS: "False"  # 个人资料查看次数
          SHOW_SHORT_INFO: "False"  # GitHub Data总览
          SHOW_LOC_CHART: "False"  # 不同年份不同季度编写的代码行数
          UPDATED_DATE_FORMAT: "%Y/%m/%d %H:%M:%S"  # 更新wakatime的时间格式
          SHOW_LINES_OF_CODE: "True"  # 代码行数
          SHOW_TOTAL_CODE_TIME: "True"  # 编码时间
          ### commit
          COMMIT_USERNAME: "GitHubActionBot"
          COMMIT_EMAIL: "action-bot@github.com"
          SHOW_COMMIT: "False"  # 提交数据统计
          SHOW_DAYS_OF_WEEK: "False"  # 一周中每天提交的次数
          
