name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # UTC+8 时区的每日 0:00 对应于 UTC 的前一天 16:00
    - cron: "0 16 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_USERNAME: "GitHubActionBot"
          COMMIT_EMAIL: "action-bot@github.com"
          SHOW_UPDATED_DATE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
